#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter Gerätetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-Sensor-THPL-BME280" id="HB-UNI-Sensor-THPL-BME280">
DEVICE="HB-UNI-Sensor-THPL-BME280"
# in der WebUI angezeigte Gerätebeschreibung
DEVICE_DESC="BME280 + TSL2591 Sensor (T\/H\/P\/Lux)"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-uni-sensor-temp-lux.png
DEVICE_THUMB=hb-uni-sensor-temp-lux_thumb.png
ADDON_DIR=/usr/local/addons/hb-pk-devices-addon
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sensor-THPL-BME280.xml

# NOTE: Firmware XML symlink and image copy are handled automatically by the rc.d script

#------------------------------------------------------------------------------
# Edit DEVDB.tcl
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Edit webui.js
webuiFile="/www/webui/webui.js"
webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi

#------------------------------------------------------------------------------
# Edit stringtable_de.txt
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="WEATHER|LUX\t\${stringTableWeather_Lux}"
if [ -z "`cat $stringtable_deFile | grep \"WEATHER|LUX\"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

#------------------------------------------------------------------------------
# Edit German translate.lang.stringtable.js
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableWeather_Lux\" : \"Helligkeit (lx)\","
if [ -z "`cat $translate_deFile | grep \"stringTableWeather_Lux\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
