#!/bin/sh

#------------------------------------------------------------------------------
DEVICE="HB-UNI-Sensor-THPL-BME280"
DEVICE_DESC="BME280 + TSL2591 Sensor (T\/H\/P\/Lux)"
DEVICE_IMG=hb-uni-sensor-temp-lux.png
DEVICE_THUMB=hb-uni-sensor-temp-lux_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sensor-THPL-BME280.xml

#------------------------------------------------------------------------------
# Undo DEVDB.tcl changes
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
        sed -i "s/\($devdescrSearch\)//g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Undo webui.js changes
webuiFile="/www/webui/webui.js"
if [ "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
        sed -i "/\($DEVICE\)/d" $webuiFile
fi

#------------------------------------------------------------------------------
# remove device_xml symlink
mount -o remount,rw /firmware 2>/dev/null || true
rm -f $FIRMWARE_FILE
mount -o remount,ro /firmware 2>/dev/null || true

#------------------------------------------------------------------------------
# remove image files
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB

#------------------------------------------------------------------------------
# Undo stringtable_de.txt
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deSearch="WEATHER|LUX"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

#------------------------------------------------------------------------------
# Undo German translate.lang.stringtable.js
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"

translate_deSearch="stringTableWeather_Lux"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
